apiVersion: v1
kind: Pod
metadata:
  name: jackwire-node-redis
  labels:
    purpose: jackwire-node-redis
    app: jackwire-node-redis
spec:
  imagePullSecrets:
    - name: regcred
  containers:
    - name: jackwire-node-redis
      image: cloud.canister.io:5000/arhturescriou/node-redis
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080
      env:
      - name: PORT
        value: '8080'
      - name: REDIS_URL
        value: redis://10.3.27.122:6379
